name: Pull Request

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-commits:
    name: Check Commitizen
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Pyhon
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Commitizen
        run: ./.internal/ci/install-cz.sh
      - name: Check Commits
        run: ./.internal/ci/version-check.sh

  build-theme:
    name: Build Theme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build
        run: ./.internal/ci/build.sh
