name: Release

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.next-version.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Pyhon
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Commitizen
        run: ./.internal/ci/install-cz.sh
      - name: Determine Next Version
        id: next-version
        run: echo "version=$(./.internal/ci/version-next.sh)" >> $GITHUB_OUTPUT

  build-theme:
    name: Build Theme
    runs-on: ubuntu-latest
    needs: version
    if: needs.version.outputs.version != ''
    env:
      VERSION: ${{ needs.version.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build
        run: ./.internal/ci/build.sh

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [version, build-theme]
    if: needs.version.outputs.version != ''
    environment: release
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Configure Git User
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Setup Pyhon
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Commitizen
        run: ./.internal/ci/install-cz.sh
      - name: Bump Version
        env:
          NEXT_VERSION: ${{ needs.version.outputs.version }}
        run: ./.internal/ci/version-bump.sh "$NEXT_VERSION"
      - name: Push
        run: git push && git push --tags && exit 0
